Adding auth trigger to pubsub
kedacore/keda pull request #1291
Opened 2020-10-25 02:23 UTC by harshthakur9030

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes #1273

2020-10-26 19:15 UTC, ahmelsayed approved these changes

2020-10-26 19:16 UTC, ahmelsayed commented
LGTM. Thanks @harshthakur9030!

2020-10-27 06:19 UTC, tomkerkhove commented
Would you mind updating our docs on https://github.com/kedacore/keda-docs/blob/master/content/docs/2.0/scalers/gcp-pub-sub.md as well please?

2020-10-27 06:20 UTC, tomkerkhove requested changes
Can you update the changelog please?
https://github.com/kedacore/keda/blob/v2/CHANGELOG.md

2020-10-27 08:09 UTC, zroubalik approved these changes
LGTM, just a minor nit in tests and as Tom mentioned, please add that to docs and add this to Changelog (Improvement section)

2020-10-27 08:09 UTC, zroubalik commented on pkg/scalers/gcp_pubsub_scaler_test.go
> +	{nil, map[string]string{"subscriptionName": "mysubscription", "subscriptionSize": "7", "credentialsFromEnv": "WRONG_CREDS"}, false},
As you mentioned in the slack, this should be revised, we don't have to keep this test case, as it is the same as the one on line 25

2020-10-28 00:02 UTC, harshthakur9030 commented
PTAL @zroubalik  @tomkerkhove ! Did the changes asked. Here's the doc PR: https://github.com/kedacore/keda-docs/pull/293

2020-10-28 05:36 UTC, tomkerkhove approved these changes

2020-10-29 08:17 UTC, zroubalik approved these changes

2020-10-29 08:17 UTC, merged