Enable goconst
kedacore/keda pull request #1296
Opened 2020-10-28 04:32 UTC by daxmc99

_Provide a description of what has been changed_

Part of https://github.com/kedacore/keda/issues/1158

Happy Hacktober 🎃

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes #

2020-10-29 08:21 UTC, zroubalik requested changes

2020-10-29 08:21 UTC, zroubalik commented on pkg/scalers/metrics_api_scaler.go
> +		if config.TriggerMetadata["method"] == promQuery {
It is not ideal to reference const from another scaler, we should introduce a one specific for this scaler instead

2020-11-10 12:13 UTC, zroubalik commented
@daxmc99 hi, any update on this please?

2020-11-18 11:28 UTC, Shubham82 commented
NOTE: I am working on this and i have created a new PR for this. #1341

2020-11-18 11:49 UTC, closed without merging

2020-11-18 18:23 UTC, daxmc99 commented
Thanks for picking this up @Shubham82 
Sorry for the delay @zroubalik

2020-11-18 18:24 UTC, zroubalik commented
@daxmc99 no worries :)

2020-11-19 12:13 UTC, Shubham82 commented
Hi @daxmc99  
Are you planning to enable gocritic or not.