chore: use different metric default name
kedacore/keda pull request #1429
Opened 2020-12-16 06:35 UTC by yquansah

Signed-off-by: Yoofi Quansah <yqsummon@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes #

2020-12-16 12:23 UTC, zroubalik requested changes

2020-12-16 12:23 UTC, zroubalik commented on pkg/scalers/influxdb_scaler.go
> +	if val, ok := config.TriggerMetadata["metricName"]; ok {
Could you please take a look on how Postrgresql scaler is done? We need to mask certain characters in the metricName:
 https://github.com/kedacore/keda/blob/cfebd9e0384c54f23caaeb0074866d5685f0c77a/pkg/scalers/postgresql_scaler.go#L118-L131

For influxdb I think you can use the combination of `prefix (infludb-) + url + organisationName`

2020-12-17 12:05 UTC, zroubalik approved these changes
LGTM, thanks @yquansah !

2020-12-17 12:06 UTC, zroubalik commented
@yquansah there's a problem in the linter :(

2020-12-17 20:16 UTC, yquansah commented
@zroubalik Addressed

2020-12-18 10:18 UTC, zroubalik approved these changes
LGTM, thanks @yquansah !

2020-12-18 10:18 UTC, merged