Add DynamoDB Scaler
kedacore/keda pull request #2486
Opened 2022-01-16 19:45 UTC by samueleresca

Related to Issue #2482 

Signed-off-by: Samuele Resca <samuele.resca@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated

Fixes #

2022-02-22 05:55 UTC, tomkerkhove commented
Thanks for your PR! Would you mind opening and linking a PR for the docs please?

2022-02-28 13:03 UTC, zroubalik reviewed
Looking good, just a few minor nits on formatting.

Also a big topic is e2e testing. Do you think you can implement e2e tests for this scaler, similar to this https://github.com/kedacore/keda/tree/main/tests? We should have KEDA related AWS account soon CC @tomkerkhove

2022-02-28 13:03 UTC, zroubalik commented on pkg/scalers/aws_dynamodb_scaler.go
> +
```suggestion
```

2022-02-28 13:03 UTC, zroubalik commented on pkg/scalers/aws_dynamodb_scaler.go
> +
```suggestion
```

2022-02-28 13:03 UTC, zroubalik commented on pkg/scalers/aws_dynamodb_scaler.go
> +
```suggestion
```

2022-02-28 13:03 UTC, zroubalik commented on pkg/scalers/aws_dynamodb_scaler.go
> +
```suggestion
```

2022-02-28 14:49 UTC, samueleresca commented on pkg/scalers/aws_dynamodb_scaler.go
> +	kedautil "github.com/kedacore/keda/v2/pkg/util"
Now it should be fine

2022-02-28 14:51 UTC, samueleresca commented
> Looking good, just a few minor nits on formatting.
> 
> Also a big ask is e2e testing. Do you think you can implement e2e tests for this scaler, similar to this https://github.com/kedacore/keda/tree/main/tests? We should have KEDA related AWS account soon CC @tomkerkhove

I'm happy to implement the e2e tests for this. Should I do it in this PR?

2022-02-28 14:56 UTC, zroubalik commented
> > Looking good, just a few minor nits on formatting.
> > Also a big ask is e2e testing. Do you think you can implement e2e tests for this scaler, similar to this https://github.com/kedacore/keda/tree/main/tests? We should have KEDA related AWS account soon CC @tomkerkhove
> 
> I'm happy to implement the e2e tests for this. Should I do it in this PR?

Yes please :)

2022-02-28 18:21 UTC, zroubalik commented on pkg/scalers/aws_dynamodb_scaler.go
> +			Name: GenerateMetricNameWithIndex(c.metadata.scalerIndex, kedautil.NormalizeString(fmt.Sprintf("aws-dynamodb-%s", c.metadata.tableName))),
Could you please move this to `parseAwsDynamoDBMetadata()` so it is called only on the first time?

You can take a look here, to see the example:
https://github.com/kedacore/keda/blob/b6bc7b754e2b5145c45895126e9dc57e86ab8816/pkg/scalers/datadog_scaler.go#L134

2022-03-02 10:59 UTC, samueleresca commented
> > > Looking good, just a few minor nits on formatting.
> > > Also a big ask is e2e testing. Do you think you can implement e2e tests for this scaler, similar to this https://github.com/kedacore/keda/tree/main/tests? We should have KEDA related AWS account soon CC @tomkerkhove
> > 
> > 
> > I'm happy to implement the e2e tests for this. Should I do it in this PR?
> 
> Yes please :)

Regarding the e2e testing. I'm considering spanning up an instance using the following image for testing purposes: https://hub.docker.com/r/amazon/dynamodb-local. Until we don't have an AWS account. It should mimic the dynamodb on AWS, except for the fact that multiple regions are not supported

2022-03-07 18:50 UTC, samueleresca commented
@zroubalik  I updated the PR with the tests.  I executed the E2E test locally with my personal subscription and looks good to me. Let me know when you have the account available.

2022-03-11 11:13 UTC, zroubalik commented
> @zroubalik I updated the PR with the tests. I executed the E2E test locally with my personal subscription and looks good to me. Let me know if I can do something else.

@JorTurFer @tomkerkhove how should we approach this? Do we know if there's any progress on the AWS account from CNCF?

2022-03-11 11:14 UTC, zroubalik requested changes
Nit

2022-03-11 11:14 UTC, zroubalik commented on tests/scalers/aws-dynamodb.test.ts
> +  sh.exec(`kubectl create namespace ${dynamoDBNamespace}`)
There's a helper method for creating namespace. please use it.

2022-03-11 12:18 UTC, JorTurFer commented
> > @zroubalik I updated the PR with the tests. I executed the E2E test locally with my personal subscription and looks good to me. Let me know if I can do something else.
> 
> @JorTurFer @tomkerkhove how should we approach this? Do we know if there's any progress on the AWS account from CNCF?

If the e2e test is running, I'd keep it commented and I'd enable it when the account is ready. We already have other scalers without any e2e test, so I wouldn't block this PR. 
Other option is using [`DynamoDB Local`](https://hub.docker.com/r/amazon/dynamodb-local) but I'm not sure if that development version could be enough for our e2e test case. Even if the local version is enough, I'd prefer using the real version, but this is an option

2022-03-11 12:32 UTC, zroubalik commented
> > > @zroubalik I updated the PR with the tests. I executed the E2E test locally with my personal subscription and looks good to me. Let me know if I can do something else.
> > 
> > 
> > @JorTurFer @tomkerkhove how should we approach this? Do we know if there's any progress on the AWS account from CNCF?
> 
> If the e2e test is running, I'd keep it commented and I'd enable it when the account is ready. We already have other scalers without any e2e test, so I wouldn't block this PR. Other option is using [`DynamoDB Local`](https://hub.docker.com/r/amazon/dynamodb-local) but I'm not sure if that development version could be enough for our e2e test case. Even if the local version is enough, I'd prefer using the real version, but this is an option

Yeah, let's disable e2e tests for now and enable once we have the account.

2022-03-12 09:15 UTC, tomkerkhove commented
No AWS account yet indeed. I will check

2022-03-16 09:24 UTC, zroubalik commented on CHANGELOG.md
> +- **General:** Automatically run end-to-end tests on ARM ([#2262]https://github.com/kedacore/keda/issues/2262))
Could you please include just the relevant info? and use the format as it is used for other new scalers (please also include AWS in the name)

2022-03-16 09:24 UTC, zroubalik commented on tests/scalers/aws-dynamodb.test.ts
> +import test from 'ava'
Could you please comment the whole content of the file, so it is not being executed, we will enable it once we have AWS account in place.

2022-03-17 20:00 UTC, JorTurFer reviewed
You have done an awesome job! 🤟🤟🤟 
Thanks for this contribution and all the effort, LGTM
Only 1 small nit inline

2022-03-18 07:54 UTC, JorTurFer approved these changes
LGTM!
Thanks for the huge effort!

2022-03-18 08:03 UTC, zroubalik approved these changes
LGTM, thanks for the contribution! Great job.

2022-03-18 08:05 UTC, zroubalik requested changes

2022-03-18 08:05 UTC, zroubalik commented on CHANGELOG.md
> +- **General:** Automatically release container image for ARM ([#2263]https://github.com/kedacore/keda/issues/2263))
I missed this, could you please remove the unrelated entries

2022-03-22 09:03 UTC, merged