prometheus: change threshold type value to float64
kedacore/keda pull request #2730
Opened 2022-03-11 09:52 UTC by alileza

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2729

2022-03-11 11:34 UTC, JorTurFer commented
/run-e2e prometheus*

2022-03-11 11:40 UTC, JorTurFer requested changes
Thanks for your contribution! ❤️ 

I think that this change is not enough because the places where this value is used still cast it into int64. For supporting this feature, these lines have to be updated too:

- https://github.com/kedacore/keda/blob/main/pkg/scalers/prometheus_scaler.go#L147
- https://github.com/kedacore/keda/blob/main/pkg/scalers/prometheus_scaler.go#L244

The first line is when KEDA generates the HPA, that HPA should receive that threshold using mili.
The second line is when KEDA exposes the metric. If we round to int this value, doesn't make sense having float in threshold

2022-03-11 11:40 UTC, JorTurFer commented on CHANGELOG.md
> +- **Prometheus Scaler:** Parse threshold as `float64` instead of `int` ([#2729](https://github.com/kedacore/keda/issues/2729))
Could you sort this alphabetically please?

2022-03-11 13:03 UTC, alileza commented
@JorTurFer oh you're right, it wasn't covered by unit test, good catch I'll make the change!

2022-03-11 13:26 UTC, alileza commented
this is interesting, https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go this dependency is not supporting float64

```
// Note that the quantity will NEVER be internally represented by a
// floating point number. That is the whole point of this exercise.
```

and if you see a few other scalers like [influxdb](https://github.com/kedacore/keda/blob/main/pkg/scalers/influxdb_scaler.go#L212), [huawei_cloudeye](https://github.com/kedacore/keda/blob/main/pkg/scalers/huawei_cloudeye_scaler.go#L237)

and a few others also facing the same issue. But casting float64 that would cause misbehaviour as well...

2022-03-11 16:17 UTC, JorTurFer commented
Probably nobody has taken into account this...
Maybe I'm overthinking but without that change, I feel the support to float64 a bit useless because it's only internal. Nor HPA nor ScaledJobs will use the float for nothing

2022-03-14 09:44 UTC, zroubalik commented
Yeah we should stick with the current implementation, it doesn't make sense to support float which will be immediately converted to integer.

Users can always multiply the prom query result and threshold with 100 to get higher precision.

2022-03-16 09:51 UTC, closed without merging