fix: trim so name when is longer than 63 chars
kedacore/keda pull request #2995
Opened 2022-05-03 23:31 UTC by JorTurFer

Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

If the SO Name is longer than 63 characters, KEDA fails because that length is valid for the SO Name but not for other resources where it's used. This PR trims the SO Name when is longer than 63 characters on every place where is needed

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes https://github.com/kedacore/keda/issues/2915

2022-05-03 23:32 UTC, JorTurFer commented
/run-e2e

2022-05-04 05:45 UTC, tomkerkhove commented
How do you resolve it when `verylongnaaa[..]aame-1` & `verylongnaaa[..]aame-2` are 65 chars long?

2022-05-04 06:07 UTC, JorTurFer commented
In than case there is a conflict and the hpa will not be created. We can remove the extra characters from the beginning or from the middle, but there are cases for every situation.
Other option to simplify this is just throw an error if the scaled object is longer than IDK, 55 characters (remember that the add things to the so name in some cases so we extend the length)

2022-05-04 06:09 UTC, JorTurFer commented
Or we could also remove the odd characters or something like that 🤔

2022-05-04 06:13 UTC, tomkerkhove commented
Or we assign a guid internally and use that but I guess that defeats the discoverability for our end-users - unless it's surfaced in our k get scaledobject

2022-05-04 06:23 UTC, JorTurFer commented
> Or we assign a guid internally and use that but I guess that defeats the discoverability for our end-users - unless it's surfaced in our k get scaledobject

You are right, it's another option, but I agree that the user experience will be horrible in that case. The main problem is that it's not only an internal thing (like label selectors), the HPA name is generated based on SO Name and it has a length constraint AFAIK

2022-05-04 07:06 UTC, zroubalik commented
As mentioned, this could introdue conflict when there will be a couple of SO with a similar long name. Also the label set on ScaledObject is being used to identify correct SO that is needed by HPA controller to drive the scaling.

We should design some robust solution (probably introducing some uids), but I think that we don't have to block 2.7 on this and postpone it to 2.8

2022-05-04 07:08 UTC, tomkerkhove commented
Agreed - I think unique IDs are the only solid approach for this which we can surface in our end-user experience.

2022-05-04 07:25 UTC, JorTurFer commented
I agree too. Let's talk about this with calm for v2.8

2022-05-04 08:07 UTC, tomkerkhove requested changes
Just for sake of process

2022-05-04 08:07 UTC, tomkerkhove commented on controllers/keda/hpa.go
> +		"app.kubernetes.io/part-of":    kedacontrollerutil.Trim(scaledObject.Name, 63),
As discussed, we need a more robust solution

2022-05-04 15:59 UTC, rwkarg commented
Another approach I've seen is if the string is over the limit (ex. >63), cut it down to a smaller number (63-7=56) and add a hash of the full original value (`-` plus a 6 character hash). 
So `long-value-...-the-rest-of-the-thing` becomes `long-value-...-the-re-39f5a2`.

Doesn't guarantee there won't be a collision, but it's extremely unlikely.

2022-05-04 18:51 UTC, zroubalik commented
Agree, I have been thinking about something like this.

We need to evaluate all the options and select the best  one. We still have a time for 2.8

2022-05-09 17:39 UTC, JorTurFer commented
/run-e2e

2022-05-09 18:56 UTC, JorTurFer commented
/run-e2e

2022-05-09 19:13 UTC, JorTurFer commented
/run-e2e

2022-05-09 19:18 UTC, closed without merging