test: move account id to trigger auth on integration test for new relic
kedacore/keda pull request #3027
Opened 2022-05-09 20:28 UTC by pragmaticivan

Moves account id to TriggerAuthentication for New Relic Integration Tests
### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates to https://github.com/kedacore/keda/issues/2883

2022-05-12 09:54 UTC, zroubalik requested changes
@pragmaticivan it would be better if we create a separate test for this, instead of modifing the existing one. (The original approach is still valid imho).

2022-05-12 16:19 UTC, pragmaticivan commented
Makes sense @zroubalik I actually just wanted to run that test in the CI, was not sure if integrations were triggered in PRs

2022-05-12 16:22 UTC, JorTurFer commented
> Makes sense @zroubalik I actually just wanted to run that test in the CI, was not sure if integrations were triggered in PRs

e2e test are not automatically triggered, but we can trigger them if you want

2022-05-12 16:23 UTC, JorTurFer commented
/run-e2e new-relic*

2022-05-12 16:39 UTC, JorTurFer commented
/run-e2e new-relic*

2022-05-12 16:57 UTC, pragmaticivan commented
@JorTurFer I'm suspecting my latest change was correct but was not passed down (omitting account ID for new relic). will try to investigate why. Hopefully I can get integration tests running in my machine soon.

2022-05-12 17:01 UTC, JorTurFer commented
no no, the problem is in our cluster, 100% sure
We have recently merged some  big changes from infra pov.

2022-05-12 17:40 UTC, JorTurFer commented
/run-e2e new-relic*

2022-05-12 18:24 UTC, JorTurFer commented
/run-e2e new-relic*

2022-05-12 19:50 UTC, JorTurFer commented
/run-e2e new-relic*

2022-05-16 19:30 UTC, pragmaticivan commented
Thanks @JorTurFer !

2022-05-16 19:30 UTC, closed without merging