wip - add trivy scanner for code
kedacore/keda pull request #3294
Opened 2022-06-27 17:11 UTC by JorTurFer

Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

Relates to #

2022-06-28 06:52 UTC, tomkerkhove requested changes
Please make sure to update our security policy as well

2022-06-29 21:36 UTC, pragmaticivan commented
The `severity` field for this action defaults to `UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL`. 

Code LGTM although you might get some `extra noise` by not limiting that out for only `MEDIUM,HIGH,CRITICAL`.

2022-06-30 06:05 UTC, JorTurFer commented
> The `severity` field for this action defaults to `UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL`. 
> 
> Code LGTM although you might get some `extra noise` by not limiting that out for only `MEDIUM,HIGH,CRITICAL`.

Yeah, I know that default severity includes lot of things but atm even that, we don't have any alert, so maybe it's better to have the most secure thing and just checking the noise. (but I agree also with modifying it)

2022-06-30 07:43 UTC, tomkerkhove reviewed
This is great, but if we merge this then all PRs will be blocked because of the vulnerabilities.

Can you patch them as part of this PR please?

2022-06-30 07:43 UTC, tomkerkhove commented on SECURITY.md
> +- [Trivy](https://aquasecurity.github.io/trivy/latest/) helps us with identifying vulnerabilities in our dependencies and docker images to raise awareness.
```suggestion
- [Trivy](https://aquasecurity.github.io/trivy/latest/) helps us with identifying vulnerabilities in our dependencies and docker images to raise awareness as part of our CI.
```

2022-06-30 08:14 UTC, JorTurFer commented
> This is great, but if we merge this then all PRs will be blocked because of the vulnerabilities.
> 
> Can you patch them as part of this PR please?

Based on [lastest execution](https://github.com/kedacore/keda/runs/7116989844?check_suite_focus=true) there is not any vulnerability in the code

2022-06-30 09:05 UTC, tomkerkhove approved these changes

2022-06-30 09:18 UTC, zroubalik approved these changes

2022-06-30 11:08 UTC, merged

2022-06-30 11:37 UTC, zroubalik commented
One thing, don't we want to run this in nightly test runs as well? Or is that an overkill?

2022-06-30 13:31 UTC, JorTurFer commented
> One thing, don't we want to run this in nightly test runs as well? Or is that an overkill?

good point, IDK because we do commits really often and this is executed on every merge to main, so maybe yes or maybe it's overkill, we could just add it, it's free xD