Enhance azure data explorer scaler metric name with trigger.metadata.metricName
kedacore/keda pull request #3589
Opened 2022-08-24 08:32 UTC by cdlliuy

PR to address https://github.com/kedacore/keda/issues/3588

2022-08-24 08:35 UTC, cdlliuy commented
add @v-shenoy  for review

2022-08-24 08:57 UTC, v-shenoy requested changes

2022-08-24 08:57 UTC, v-shenoy commented on pkg/scalers/azure_data_explorer_scaler.go
> +	metadataName, _ := getParameterFromConfig(config, "metricName", false)
```suggestion
	metricName, err := getParameterFromConfig(config, "metricName", false)
```

2022-08-24 09:01 UTC, v-shenoy reviewed
Update the CHANGELOG with this change.

Could you also add a unit test checking the metric name is being used?

2022-08-24 11:19 UTC, v-shenoy commented
Hmm, there has been some discussion regarding the need for this parameter - https://github.com/kedacore/keda/pull/3182

@JorTurFer @zroubalik can give their thoughts about this.

2022-08-24 11:34 UTC, JorTurFer commented
Let's discuss this in the issue, I wrote a comment there
https://github.com/kedacore/keda/issues/3588#issuecomment-1225547340

2022-08-25 14:04 UTC, cdlliuy commented on pkg/scalers/azure_data_explorer_scaler.go
> +	metadataName, _ := getParameterFromConfig(config, "metricName", false)
@v-shenoy ,  updated in another approach. please help to review again.

2022-09-08 04:35 UTC, cdlliuy commented
close this PR since the solution is changed

2022-09-08 04:35 UTC, closed without merging