fix: issue [#915](https://github.com/kedacore/keda-docs/issues/915#issue-1351191625)
kedacore/keda pull request #3599
Opened 2022-08-25 16:54 UTC by WindNotStop

Signed-off-by: taenyang [ytz199610@gmail.com](mailto:ytz199610@gmail.com)

_Provide a description of what has been changed_

Fixes issue [#915](https://github.com/kedacore/keda-docs/issues/915#issue-1351191625)

2022-09-12 19:46 UTC, JorTurFer commented
Sorry, I'm checking where is closed the scaler before the line you have removed and I can't find it. Could you point me to it?

2022-09-14 16:57 UTC, WindNotStop commented
> Sorry, I'm checking where is closed the scaler before the line you have removed and I can't find it. Could you point me to it?
The call chain is as follows:
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/pkg/scaling/cache/scalers_cache.go#L231
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/pkg/scaling/cache/scalers_cache.go#L227
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/pkg/scaling/scale_handler.go#L209
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/pkg/scaling/scale_handler.go#L113
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/controllers/keda/scaledobject_controller.go#L440
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/controllers/keda/scaledobject_finalizer.go#L37
https://github.com/kedacore/keda/blob/23bc75fc51a2aa43b96f830590ddf45dc0cef60c/controllers/keda/scaledobject_controller.go#L146

2022-09-14 19:06 UTC, JorTurFer approved these changes
You are right, thanks for the explanation 🙇 
LGTM!
WDYT @zroubalik ? Am I missing something?

2022-11-21 16:58 UTC, JorTurFer commented
Ping @zroubalik

2022-11-23 11:29 UTC, tomkerkhove requested changes

2022-12-06 00:14 UTC, WindNotStop commented on CHANGELOG.md
> +- **General:** A problem with PushScaler ([#3881](https://github.com/kedacore/keda/issues/3881))
Agree. What do you think it looks now?

2022-12-07 13:00 UTC, zroubalik approved these changes

2022-12-07 13:00 UTC, zroubalik commented
/run-e2e

2022-12-07 13:02 UTC, zroubalik commented
/run-e2e external*

2022-12-07 14:20 UTC, tomkerkhove approved these changes

2022-12-07 14:20 UTC, merged