fix(azure blob scaler): initialize logger #3811
kedacore/keda pull request #3812
Opened 2022-11-03 20:52 UTC by tomasgiden

The logger in Azure blob scaler was initialized but not saved. Thus, when logging an error, the logger segfaulted.

In addition, a very minor improvement of the log message which caused the segfault.

Note: I am not a GO developer and I have not tested it locally. 

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3811

Relates to #

2022-11-03 21:00 UTC, JorTurFer approved these changes
Thanks for the fix! ❤️

2022-11-03 21:01 UTC, JorTurFer requested changes

2022-11-03 21:01 UTC, JorTurFer commented on pkg/scalers/azure_blob_scaler.go
> +		logger:      logger
```suggestion
		logger:      logger,
```

2022-11-03 21:01 UTC, JorTurFer commented on pkg/scalers/azure_blob_scaler.go
> +		logger:      logger
There is a missing `,` here

2022-11-03 21:02 UTC, JorTurFer commented
We also require that every commit is signed (DCO check), could you sign your commits?
https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what

2022-11-04 08:53 UTC, tomasgiden commented on pkg/scalers/azure_blob_scaler.go
> +		logger:      logger
Doh, I had one job! Fixed.

2022-11-04 09:41 UTC, JorTurFer approved these changes
Thanks a ton for the fix! ❤️

2022-11-04 09:41 UTC, merged