Added panel regarding ammount of HPA, include #3911
kedacore/keda pull request #3934
Opened 2022-11-29 22:18 UTC by yuvalweber

_Provide a description of what has been changed_

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

Relates to #

2022-11-29 22:36 UTC, zroubalik requested changes
Hi, could you please also update the Dashboard to target metrics exposed in KEDA Operator, we have just recently changed this a little bit. KEDA Operator is the ultimate source of prom metrics (prom metrics from Metrics Server are deprecated and will be removed).

There are the same metrics exposed by Operator, but they are slightly renamed, see for details: https://github.com/kedacore/keda/issues/3919

2022-11-29 22:50 UTC, yuvalweber commented
Added 😄 @zroubalik

2022-11-30 07:59 UTC, tomkerkhove commented
Would you mind posting a screenshot please?

2022-11-30 07:59 UTC, tomkerkhove approved these changes

2022-11-30 08:00 UTC, tomkerkhove commented on config/grafana/keda-dashboard.json
> +          ]
Let's use `keda-demo`

2022-11-30 08:00 UTC, tomkerkhove commented on config/grafana/keda-dashboard.json
> +          "value": "s0-prometheus-nginx_connections_active_keda"
Let's remove reference to nginx

2022-11-30 08:28 UTC, yuvalweber commented
> Would you mind posting a screenshot please?
<img width="1653" alt="Screen Shot 2022-11-30 at 10 18 52" src="https://user-images.githubusercontent.com/61949879/204745583-4142ed69-9a7b-4039-8390-329842fc011c.png">

2022-11-30 09:56 UTC, tomkerkhove commented
Do we want to see just over time or also current? We might want to add a gauge?
https://grafana.com/docs/grafana/v9.0/visualizations/#gauge

2022-11-30 11:08 UTC, yuvalweber commented
> Do we want to see just over time or also current? We might want to add a gauge? https://grafana.com/docs/grafana/v9.0/visualizations/#gauge

Do you want to add a new one or to replace the current one with gauge?

2022-12-01 07:18 UTC, tomkerkhove commented
It's just an idea but I would add both

2022-12-02 07:02 UTC, yuvalweber commented
hey @zroubalik can you comment regarding this change?

2022-12-02 07:14 UTC, yuvalweber commented
<img width="1590" alt="Screen Shot 2022-12-02 at 9 12 00" src="https://user-images.githubusercontent.com/61949879/205236469-69e36ce3-d01d-4f46-88d9-954265d4af8b.png">
 also tried to added this as a gauge and I want your opinions about the look (I liked the time based better because I found the option using the graph to show the current vs max when it let you shows what the max value is).
But please also comment on this and if you think it's helpful I'll upload it so we could deliver the grafana dashboard to users 😄  @tomkerkhove

2022-12-02 08:18 UTC, tomkerkhove commented
I think both are perfect - Left shows current status easily, right you can see it over time if you want more details.

What are your thoughts @zroubalik @JorTurFer ?

2022-12-02 20:41 UTC, zroubalik approved these changes
Looking good.

2022-12-03 15:49 UTC, yuvalweber commented
So I'll add the second panel today to the PR and merge ok?
@tomkerkhove @zroubalik

2022-12-03 17:47 UTC, zroubalik commented
> So I'll add the second panel today to the PR and merge ok? @tomkerkhove @zroubalik

yeah :)

2022-12-03 20:54 UTC, yuvalweber commented
I can't seem to be authorize to merge to this branch so whenever you can please merge 😄

2022-12-04 12:00 UTC, tomkerkhove commented
> I can't seem to be authorize to merge to this branch so whenever you can please merge 😄

That is by design :)

Thank you!

2022-12-04 12:00 UTC, merged

2022-12-07 08:58 UTC, tomkerkhove commented
@yuvalweber Do you have an example screenshot of the full dashboard that we can add to our release blog post?

2022-12-08 08:25 UTC, yuvalweber commented
yeah of course I'll do it today @tomkerkhove

2022-12-12 10:03 UTC, tomkerkhove commented
@yuvalweber Did you manage to create one? If not, no problem.

2022-12-12 14:15 UTC, yuvalweber commented
Sorry for late response.
This is what I have @tomkerkhove 
![image](https://user-images.githubusercontent.com/61949879/207067525-fde1328e-f48c-4cad-8b3c-b456640a18c3.png)