feat: Allow unsafeSsl for artemis connections
kedacore/keda pull request #4081
Opened 2023-01-09 10:42 UTC by NoUseFreak

_Provide a description of what has been changed_

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #

Relates to #

2023-01-10 17:01 UTC, JorTurFer reviewed
Looking good, only 2 small nits inline

2023-01-10 17:01 UTC, JorTurFer commented on pkg/scalers/artemis_scaler.go
> +func parseArtemisAuth(config *ScalerConfig) (*authentication.AuthMeta, error) {
As you have changed to `AuthMeta`, there is a helper to parse it `GetAuthConfigs` with all the options (event the scaler doesn't support all, we can use the helper and ignore invalid options)

2023-01-10 17:01 UTC, JorTurFer commented on pkg/scalers/artemis_scaler.go
> +			return nil, fmt.Errorf("error parsing %s: %s", unsafeSsl, err)
```suggestion
			return nil, fmt.Errorf("error parsing %s: %w", unsafeSsl, err)
```

2023-01-10 17:02 UTC, JorTurFer commented
/run-e2e artemis*

2023-01-16 16:29 UTC, JorTurFer approved these changes

2023-01-16 16:39 UTC, zroubalik approved these changes

2023-01-16 16:40 UTC, zroubalik requested changes

2023-01-16 16:40 UTC, zroubalik commented on CHANGELOG.md
> +- **Artemis**: Add unsafeSsl option ([#4081](https://github.com/kedacore/keda/pull/4081))
please move this below "General" entries

2023-01-16 16:40 UTC, zroubalik commented
/run-e2e artemis*

2023-01-17 09:29 UTC, zroubalik commented on CHANGELOG.md
> +- **Artemis**: Add unsafeSsl option ([#4081](https://github.com/kedacore/keda/pull/4081))
```suggestion
- **Artemis Scaler**: Add unsafeSsl option ([#4081](https://github.com/kedacore/keda/pull/4081))
```

2023-02-06 11:24 UTC, JorTurFer commented
Does `unsafeSsl` make sense once the [customCA](https://github.com/kedacore/keda/pull/4191) is merged?

2023-04-10 09:47 UTC, NoUseFreak commented
Closing as customCA can solve the issue

2023-04-10 09:47 UTC, closed without merging