fix: Added port information check in ClusterIPAddress
kedacore/keda pull request #4162
Opened 2023-01-28 21:35 UTC by ithesadson

Signed-off-by: ithesadson <thesadson@gmail.com>

Since the change I made before was a breaking change, I just fix the mistake and send a pr again.
Issue : #4110
Previous PR: #4079

If the clusterIPAddress contains port information, checking if the port information is entered in the clusterIPAddress will cause some errors.

Error example in current code: User enters the following values.
clusterIPAddress: "https://cassandra.test/"
port: "9042"
->Expected clusterIPAddress : https://cassandra.test:9042/
The actual clusterIPAddress: https://cassandra.test/

### Checklist
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

2023-01-30 10:30 UTC, zroubalik commented on CHANGELOG.md
> +- **Cassandra Scaler**: Checking whether the port information is entered in the ClusterIPAddres is done correctly. ([#4110](https://github.com/kedacore/keda/issues/4110))
nit, please sort alphabetically

2023-01-30 11:02 UTC, zroubalik commented
/run-e2e cassandra*

2023-01-30 12:34 UTC, zroubalik approved these changes
LGTM, thanks for the contribution!

2023-01-30 12:35 UTC, zroubalik requested changes
One more thing, do you think you can add unit test for this fix? https://github.com/kedacore/keda/blob/main/pkg/scalers/cassandra_scaler_test.go

2023-02-04 18:53 UTC, ithesadson commented
I added the unit test. But e2e-tests has been running for about 5 days and has not finished yet. Is there any problem with my unit test?

2023-02-06 09:17 UTC, zroubalik commented
/run-e2e cassandra*

2023-02-06 09:17 UTC, zroubalik commented
@ithesadson maintainers need to start e2e tests, I've just triggered them

2023-02-06 10:34 UTC, zroubalik approved these changes
LGTM, thanks for the fix!

2023-02-06 10:34 UTC, merged