fix: Azure Pipelines Scaler uses correct endpoint when demands are set  (#4387)
kedacore/keda pull request #4401
Opened 2023-03-22 16:41 UTC by Eldarrin

Added a simple hotfix to grab different querystring excluding top when parent is required,

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #
#4387 

Relates to #

2023-03-24 07:59 UTC, JorTurFer approved these changes

2023-03-24 07:59 UTC, JorTurFer commented
/run-e2e pipelines*

2023-03-24 09:01 UTC, JorTurFer commented on tests/scalers/azure/azure_pipelines_adv/azure_pipelines_adv_test.go
> +	testName = "azure-pipelines-test"
Use other namespace than the already e2e test for avoid conflicts 
```suggestion
	testName = "azure-pipelines-demands-test"
```

2023-03-24 09:43 UTC, JorTurFer commented
/run-e2e pipelines*

2023-03-24 12:23 UTC, Eldarrin commented
@JorTurFer  I think running the new tests in parallel with the old tests upset ADO :)

2023-03-26 20:25 UTC, Eldarrin commented
I can mitigate it, does your copy of ADO support running parallel self hosted jobs? The basic ado account doesn’t

2023-03-26 20:29 UTC, JorTurFer commented
> I can mitigate it, does your copy of ADO support running parallel self hosted jobs? The basic ado account doesn’t

I think so:
![image](https://user-images.githubusercontent.com/36899226/227802863-0fee6161-41df-4726-a667-5bd406383bac.png)

2023-03-26 20:31 UTC, Eldarrin commented
Ok, will do in the morning and update

2023-03-26 20:32 UTC, JorTurFer commented
> Ok, will do in the morning and update

Sure, no rush! I have just checked GH after a disconnecting weekend 😄

2023-03-27 17:49 UTC, JorTurFer commented
> Ok, so new patch should allow e2e to run in parallel, can't really test at home as only have a basic account for ADO.
You will need to add a new agent pool (can be empty), change the new pipeline to point to the new pool and put the poolname as the new .env variable added for AZURE_DEVOPS_DEMAND_POOL_NAME=

@tomkerkhove, Could you do it? I don't have enough permissions in AzDO org

2023-03-27 17:55 UTC, JorTurFer commented
I guess that we need to update also the pipeline definition to use the new agent, right?

2023-03-27 17:55 UTC, JorTurFer commented
/run-e2e pipelines*

2023-03-27 21:20 UTC, JorTurFer requested changes
Could you add a record in the changelog? I didn't notice it before

2023-03-27 21:43 UTC, Eldarrin commented
> Could you add a record in the changelog? I didn't notice it before

Will do in the morning :)

2023-03-28 11:06 UTC, JorTurFer approved these changes

2023-03-28 11:45 UTC, merged