support OAuth for pulsar scaler
kedacore/keda pull request #4709
Opened 2023-06-19 14:40 UTC by mingmcb

support OAuth for pulsar scaler
### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to #4700

Relates to https://github.com/kedacore/keda-docs/pull/1161

2023-06-19 14:51 UTC, mingmcb commented
The PR for document is https://github.com/kedacore/keda-docs/pull/1161

2023-06-21 07:14 UTC, zroubalik commented
/run-e2e pulsar

2023-06-21 09:18 UTC, zroubalik reviewed
Looking great, my only concern is about exposing auth data in the trigger metadata, see: https://github.com/kedacore/keda-docs/pull/1161#pullrequestreview-1490251516

2023-06-22 06:52 UTC, zroubalik commented
/run-e2e pulsar

2023-06-22 07:33 UTC, zroubalik requested changes
please change the format for `scope`

2023-06-22 07:33 UTC, zroubalik commented on pkg/scalers/authentication/authentication_helpers.go
> +			if authParams["scope"] != "" {
could you please trim the string first and change the format to accept **a comma separated list* of scopes?  To be consistent with the rest of the config.

2023-06-22 07:33 UTC, zroubalik commented on pkg/scalers/pulsar_scaler.go
> +			auth.Scopes = strings.Split(config.TriggerMetadata["scope"], " ")
could you please trim the string first and change the format to accept *a comma separated list of scopes? To be consistent with the rest of the config.

2023-07-03 08:09 UTC, zroubalik commented on CHANGELOG.md
> +- **Pulsar Scaler**: Add support for OAuth extensions ([#4700](https://github.com/kedacore/keda/issues/4700))
Please move this to unreleased section

2023-07-03 08:09 UTC, zroubalik commented on pkg/scalers/authentication/authentication_helpers.go
> +			scope := strings.ReplaceAll(authParams["scope"], " ", "")
isn't `strings.TrimSpace()` better?

2023-07-03 08:09 UTC, zroubalik commented on pkg/scalers/pulsar_scaler.go
> +		scope := strings.ReplaceAll(config.TriggerMetadata["scope"], " ", "")
isn't `strings.TrimSpace()` better?

2023-07-07 09:52 UTC, zroubalik commented
This is great, there's also a proposal for a generic OAuth support that I like. I wonder if we can go this direction as well for Pulsar? https://github.com/kedacore/keda/issues/4694

2023-07-07 11:07 UTC, zroubalik reviewed
Looking good, minor stuff.

2023-07-07 11:07 UTC, zroubalik commented on CHANGELOG.md
> +- **Pulsar Scaler**: Add support for OAuth extensions ([#4700](https://github.com/kedacore/keda/issues/4700))
Please move it to Improvements subsection.

2023-07-07 11:07 UTC, zroubalik commented on pkg/scalers/authentication/authentication_helpers.go
> +func ParseScope(inputStr string) []string {
Could you please add a short describtion of what this function does?

```go
// ParseScope ...
```

2023-07-07 11:07 UTC, zroubalik commented
/run-e2e pulsar

2023-07-07 11:07 UTC, zroubalik commented
> Looking great, my only concern is about exposing auth data in the trigger metadata, see: [kedacore/keda-docs#1161 (review)](https://github.com/kedacore/keda-docs/pull/1161#pullrequestreview-1490251516)

@kedacore/keda-core-contributors WDYT?

2023-07-07 12:20 UTC, mingmcb commented
> This is great, there's also a proposal for a generic OAuth support that I like. I wonder if we can go this direction as well for Pulsar? #4694

Doesn't look like #4694 is implemented, I can convert to use it if it is ready.

2023-09-13 11:07 UTC, zroubalik reviewed
@mingmcb do you think you can address the review comments? We can proceed and merge the PR then.

We are back after a summer break

2023-09-15 16:17 UTC, zroubalik commented on pkg/scalers/pulsar_scaler.go
> +	"golang.org/x/oauth2/clientcredentials"
please keep imports separated in these 3 groups: 
- internal imports 
- external libraries
- KEDA packages

2023-09-15 16:40 UTC, zroubalik commented
/run-e2e pulsar

2023-09-15 16:41 UTC, zroubalik approved these changes
LGTM

2023-09-17 15:01 UTC, JorTurFer approved these changes
LGTM

2023-09-17 15:01 UTC, JorTurFer approved these changes
LGTM

2023-09-17 15:02 UTC, merged