fix: safely parse renewable field from vault response
kedacore/keda pull request #5193
Opened 2023-11-19 15:49 UTC by kmdrn7

This PR fixes the issue where keda operator throwing panic error while using `ScaledObject` with `TriggerAuthentication` that use hashicorp vault provider authenticated using root token.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5192

2023-11-20 13:20 UTC, zroubalik commented
@dttung2905 PTAL

2023-11-20 13:25 UTC, dttung2905 commented
@kmdrn7 Thanks for the PR. 🙏
@zroubalik Let me review this PR in a few hours

2023-11-20 19:05 UTC, dttung2905 requested changes
Thanks alot for the PR. Just a minor nitpick from me :smile:

2023-11-20 22:25 UTC, kmdrn7 commented on pkg/scaling/resolver/hashicorpvault_handler_test.go
> +		assert.Len(t, secrets, 1, "Supposed to got back one secret")
updated

2023-11-21 11:15 UTC, JorTurFer commented
/run-e2e hashicorp_vault

2023-11-21 22:59 UTC, JorTurFer commented
/run-e2e hashicorp_vault

2023-11-22 00:07 UTC, merged